import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

/**
 * Lint is wired from day one on this project, deliberately: on the Stand'Up
 * build the `eslint-disable-next-line @next/next/no-img-element` comments were
 * decorative because no ESLint was ever installed.
 */
const config = [
  {
    // next-env.d.ts is generated by Next on every build — linting it is noise.
    ignores: [
      ".next/**",
      ".next-*/**", // isolated verification builds (see next.config.ts distDir)
      "out/**",
      "node_modules/**",
      "assets-raw/**",
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
